import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import { Pacifico } from "next/font/google";

const pacifico = Pacifico({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Wedding page",
	description: "Generated by Zevik",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={pacifico.className}>
				<NavigationBar />
				{children}
			</body>
		</html>
	);
}
