import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Wedding page",
	description: "Generated by Zevik",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<header>
				<NavigationBar />
			</header>
			{/* <body className={inter.className}>{children}</body> */}
		</html>
	);
}
