'use client'
import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import Error from "./error";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Wedding page",
	description: "Generated by Zevik",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavigationBar />
				{children}
			</body>
		</html>
	);
}
